#
# Copyright 2020 Xilinx, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

MK_PATH := $(abspath $(lastword $(MAKEFILE_LIST)))
CUR_DIR=$(patsubst %/,%,$(dir $(MK_PATH)))

#hw, hw_emu
TARGET?=hw

KERNEL_DIR=$(CUR_DIR)
KERNEL=hbmArbiter_2_2_2_128m_top

SRCS=$(KERNEL_DIR)/hbmArbiter_2_2_2_128m_top.cpp

XOCCFLAGS := --platform $(XILINX_PLATFORM) -t $(TARGET)  -s -g

.PHONY: all
all: $(KERNEL)_$(TARGET).xo

$(KERNEL)_$(TARGET).xo : $(SRCS)
	v++ $(XOCCFLAGS) --kernel $(KERNEL) -I. --advanced.prop kernel.$(KERNEL).kernel_flags="-std=c++0x -D__SDSVHLS__ -DHLS_NO_XIL_FPO_LIB" -c -o $@ $<

.PHONY: clean
clean:
	-rm -rf _x
	-rm -rf .Xil
	-rm -f *.xo
	-rm -f *.xo.*
	-rm -f *.log
